//------------------------------------------------------------------------
// Copyright(c) 2025 nx.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"nxvfxvst.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"nxvfxvst VST3 (64Bit)"
#else
#define stringFileDescription	"nxvfxvst VST3"
#endif
#define stringCompanyName		"nx\0"
#define stringLegalCopyright	"Copyright(c) 2025 nx."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"

#define FULL_PRODUCT_NAME	"nxvfxvst v" FULL_VERSION_STR
