#pragma once

#include <deque>
#include <SFML/System/Time.hpp>

#include "models/IParticle.hpp"
#include "models/ISerializable.hpp"
#include "models/data/ParticleLayoutData_t.hpp"
#include "models/data/Midi_t.hpp"
#include "models/InterfaceTypes.hpp"

namespace nx
{
  struct IParticleModifier : public ISerializable< E_ModifierType >
  {
    ~IParticleModifier() override = default;

    virtual void drawMenu() = 0;

    virtual void update( const sf::Time& deltaTime ) = 0;

    virtual bool isActive() const = 0;

    virtual void processMidiEvent( const Midi_t& midiEvent ) = 0;

    ///
    /// @param particleLayoutData general particle information
    /// @param particles particles generated by IParticleLayout
    /// @param outArtifacts Ownership is handed off. do NOT manage memory. artifacts are ephemeral.
    virtual void modify(
       const ParticleLayoutData_t& particleLayoutData,
       std::deque< IParticle* >& particles,
       std::deque< sf::Drawable* >& outArtifacts ) = 0;
  };
}